#!/usr/bin/env bash
#
# End-to-end runner for the HTTPS fetch tests (tests/NTest_http.lua) against a
# physical NodeMCU device over its serial link.
#
# Device selection:
#   * If NODEMCU_SERIAL is set, that port is used.
#   * Otherwise the first /dev/ttyUSB*, /dev/ttyACM*, ... is auto-selected by
#     tap-driver.expect / expectnmcu::core::autodetect_serial.
#
# WiFi credentials (needed for the network tests; without them the HTTPS tests
# self-skip on the device):
#   * NODEMCU_WIFI_SSID    - station SSID
#   * NODEMCU_WIFI_PASSWD  - station password (may be empty for open networks)
#
# Optional:
#   * NODEMCU_LFS          - path to an LFS image to flash before running.
#
# The device must already be running a firmware that includes the `http`, `tls`,
# `net` and `wifi` modules with CLIENT_SSL_ENABLE; otherwise the HTTPS tests
# report themselves skipped. This script deliberately does NOT reflash the
# application firmware (that is destructive and board-specific).
#
# Usage:
#   NODEMCU_WIFI_SSID=myssid NODEMCU_WIFI_PASSWD=secret ./tests/run-e2e-http.sh
#   NODEMCU_SERIAL=/dev/ttyUSB2 ./tests/run-e2e-http.sh

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${here}"

# --- dependency check --------------------------------------------------------
missing=()
for cmd in expect socat tclsh; do
  command -v "${cmd}" >/dev/null 2>&1 || missing+=("${cmd}")
done
if [ "${#missing[@]}" -ne 0 ]; then
  echo "Missing required tools: ${missing[*]}" >&2
  echo "On Debian/Ubuntu: sudo apt install expect socat tcl tcllib tclx8.4" >&2
  exit 1
fi

# --- device selection (report what we'll use; driver does the real pick) -----
if [ -n "${NODEMCU_SERIAL:-}" ]; then
  echo "Using serial device from NODEMCU_SERIAL: ${NODEMCU_SERIAL}"
else
  cand="$(ls /dev/ttyUSB* /dev/ttyACM* 2>/dev/null | sort | head -n1 || true)"
  if [ -z "${cand}" ]; then
    echo "No serial device found and NODEMCU_SERIAL is unset." >&2
    echo "Attach a board or set NODEMCU_SERIAL=/dev/ttyUSBx." >&2
    exit 1
  fi
  echo "Auto-selecting serial device: ${cand} (override with NODEMCU_SERIAL)"
fi

# --- assemble files to transfer ----------------------------------------------
# NTest.lua and NTestTapOut.lua must be requirable on the DUT; NTest_http.lua is
# the last argument and is the one actually run by the driver.
workdir="$(mktemp -d)"
trap 'rm -rf "${workdir}"' EXIT

# NTest and NTestTapOut must be requirable on the DUT. Compiling them to
# bytecode (.lc) before transfer avoids the on-device source compiler, whose
# RAM overhead can exhaust the heap on a TLS-enabled build. We locate a
# matching luac.cross; if none is found we fall back to shipping the .lua
# sources (fine on devices with more free heap, e.g. an LFS-based setup).
luac="${LUAC_CROSS:-}"
if [ -z "${luac}" ]; then
  for c in ./luac.cross ../luac.cross ../bin/luac.cross ../build_lc/luac.cross; do
    [ -x "${c}" ] && { luac="${c}"; break; }
  done
fi

if [ -n "${luac}" ] && [ -x "${luac}" ]; then
  echo "Precompiling NTest deps to bytecode with ${luac}"
  "${luac}" -o "${workdir}/NTest.lc"       NTest/NTest.lua
  "${luac}" -o "${workdir}/NTestTapOut.lc" utils/NTestTapOut.lua
  xfers=("${workdir}/NTest.lc" "${workdir}/NTestTapOut.lc")
else
  echo "No luac.cross found (set LUAC_CROSS); shipping .lua sources (may OOM on small devices)"
  xfers=("NTest/NTest.lua" "utils/NTestTapOut.lua")
fi

if [ -n "${NODEMCU_WIFI_SSID:-}" ]; then
  # Emit a clean Lua string literal, escaping backslashes and double-quotes.
  {
    echo '-- Auto-generated by run-e2e-http.sh; injects station credentials.'
    printf 'TEST_WIFI_SSID = %s\n'   "$(printf '%s' "${NODEMCU_WIFI_SSID}"     | sed 's/\\/\\\\/g; s/"/\\"/g; s/^/"/; s/$/"/')"
    printf 'TEST_WIFI_PASSWD = %s\n' "$(printf '%s' "${NODEMCU_WIFI_PASSWD:-}" | sed 's/\\/\\\\/g; s/"/\\"/g; s/^/"/; s/$/"/')"
  } > "${workdir}/e2e_wifi.lua"
  xfers+=("${workdir}/e2e_wifi.lua")
  echo "Injecting WiFi credentials for SSID: ${NODEMCU_WIFI_SSID}"
else
  echo "NODEMCU_WIFI_SSID unset; HTTPS network tests will self-skip on the DUT."
fi

if [ -n "${luac:-}" ] && [ -x "${luac:-}" ]; then
  "${luac}" -o "${workdir}/NTest_http.lc" NTest_http.lua
  "${luac}" -o "${workdir}/NTest_http_part2.lc" NTest_http_part2.lua
  xfers+=("${workdir}/NTest_http_part2.lc")
  xfers+=("${workdir}/NTest_http.lc")
else
  xfers+=("NTest_http_part2.lua")
  xfers+=("NTest_http.lua")
fi

# --- optional LFS flash ------------------------------------------------------
lfs_args=()
if [ -n "${NODEMCU_LFS:-}" ]; then
  lfs_args=(-lfs "${NODEMCU_LFS}")
fi

# --- run ---------------------------------------------------------------------
serial_args=()
if [ -n "${NODEMCU_SERIAL:-}" ]; then
  serial_args=(-serial "${NODEMCU_SERIAL}")
fi

echo "Running NTest_http.lua on device..."
# Prepend our package dir; keep any caller-provided TCLLIBPATH (e.g. pointing at
# a tcllib install that carries the `cmdline` package).
export TCLLIBPATH="./expectnmcu ${TCLLIBPATH:-}"
exec ./tap-driver.expect \
  "${serial_args[@]}" \
  "${lfs_args[@]}" \
  "${xfers[@]}"
