include(${CMAKE_CURRENT_LIST_DIR}/xtensa-esp8266-toolchain.cmake)

execute_process(
    COMMAND ${CMAKE_C_COMPILER} -dD -E "include/user_modules.h"
    OUTPUT_VARIABLE USER_MODULES_CONTENT
    WORKING_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/../app
) 

# Split content into lines
string(REPLACE "\n" ";" SELECTED_MODULES "${USER_MODULES_CONTENT}")
# Process each line
list(FILTER SELECTED_MODULES INCLUDE REGEX "LUA_USE_MODULES.*")

list(TRANSFORM SELECTED_MODULES REPLACE ".*LUA_USE_MODULES_([^ ;]+).*" "\\1")
list(TRANSFORM SELECTED_MODULES TOLOWER OUTPUT_VARIABLE SELECTED_MODULES)
set(SELECTED_MODULES ${SELECTED_MODULES})