name: CI

on:
  push:
    branches: [ release, cmake ]
  pull_request:
    branches: [ dev, release ]

jobs:
      

  build:
    strategy:
      fail-fast: false
      matrix:
        lua_ver: [51, 53]
        numbers: ['float']
        build: ['make', 'cmake']
        include:
          - lua_ver: 51
            numbers: 'integral'
            build: make
          - lua_ver: 51
            numbers: 'integral'
            build: cmake    
          - lua_ver: 53
            numbers: '64bit'
            build: make
          - lua_ver: 53
            numbers: '64bit'
            build: cmake
    runs-on: ubuntu-22.04

    env:
      LUA: ${{ matrix.lua_ver }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - run: pip install pyserial
      shell: bash
    - name: Build firmware
      run: |
        EXTRA_CCFLAGS=""
        if [ "${{ matrix.numbers }}" == "integral" ]; then
          EXTRA_CCFLAGS="-DLUA_NUMBER_INTEGRAL=ON"
        elif [ "${{ matrix.numbers }}" == "64bit" ]; then
          EXTRA_CCFLAGS="-DLUA_NUMBER_64BITS=ON"
        fi
        echo $EXTRA_CCFLAGS

        if [ "${{ matrix.build }}" == "make" ]; then
           make EXTRA_CCFLAGS=$EXTRA_CCFLAGS
           mv -f luac.cross.int luac.cross 2>/dev/null || true 
        else 
          cmake -B build -GNinja -DLUA=${{ matrix.lua_ver }} $EXTRA_CCFLAGS .
          cmake --build build -j12
          cmake --install build --prefix .
          ls -ll bin
          mv -f bin/luac.cross.int bin/luac.cross 2>/dev/null || true
          mv bin/luac.cross luac.cross
        fi
      shell: bash
    - name: Upload luac.cross
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}_${{ matrix.build }}
        path: luac.cross


  build_win:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - lua_ver: 51
            numbers: float
          - lua_ver: 51
            numbers: integral
          - lua_ver: 53
            numbers: float
          - lua_ver: 53
            numbers: 64bit

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install pyserial
      run: pip install pyserial
        
    - name: Build luac.cross.exe
      run: |
        $extra_flags = @{
          "float" = ""
          "integral" = "-DLUA_NUMBER_INTEGRAL=ON"
          "64bit" = "-DLUA_NUMBER_64BITS=ON"
        }
        cmake -B build $extra_flags["${{ matrix.numbers }}"] -DLUA=${{ matrix.lua_ver }}
        cmake --build build --config Release
        cmake --install build --prefix .
        gci bin
        mv bin/luac.cross.int.exe bin/luac.cross.exe -ErrorAction SilentlyContinue
        mv bin/luac.cross.exe .
      shell: pwsh
    
    - name: Upload luac.cross
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}_win
        path: luac.cross.exe

  NTest:

    strategy:
      fail-fast: false
      matrix:
        lua_ver: [51, 53]
        numbers: ['float']
        build: ['make', 'cmake']
        include:
          - lua_ver: 51
            numbers: 'integral' 
            build: make 
          - lua_ver: 51
            numbers: 'integral'
            build: cmake
          - lua_ver: 53
            numbers: '64bit'  
            build: make
          - lua_ver: 53
            numbers: '64bit'
            build: cmake
    needs: build
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: false
    - name: Download luac.cross
      uses: actions/download-artifact@v4
      with:
        name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}_${{ matrix.build }}
        path: ./
    - name: Fix file permission
      run: chmod +x luac.cross
    - name: NTest selfcheck
      run: |
        cd tests/NTest
        ../../luac.cross -e ../NTest/NTest_NTest.lua | tee log
        grep "failed. 0" log
      shell: bash
    - name: NTest hosttests
      run: |
        cd tests
        cp NTest/NTest.lua .
        ../luac.cross -e NTest_lua.lua | tee log
        (if grep  " ==>  " log ; then exit 1 ; fi)
      shell: bash


  NTest_win:

    strategy:
      fail-fast: false
      matrix:
        include:
          - lua_ver: 51
            numbers: 'float'
          - lua_ver: 53
            numbers: 'float'
          - lua_ver: 51
            numbers: 'integral'  
          - lua_ver: 53
            numbers: '64bit'  

    needs: build_win
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: false
    - name: Download luac.cross
      uses: actions/download-artifact@v4
      with:
        name: luac.cross_${{ matrix.lua_ver }}_${{ matrix.numbers }}_win
        path: ./
    - name: NTest selfcheck
      run: |
        cd tests/NTest
        ../../luac.cross.exe -e ../NTest/NTest_NTest.lua | tee log
        if ((gc log | Select-String "failed: 0") -eq $null) { 
          Throw "Errors were found during tests";
        }
      shell: pwsh
        
    - name: NTest hosttests
      run: |
        cd tests
        cp NTest/NTest.lua .
        ../luac.cross.exe -e NTest_lua.lua | tee log
        if ((gc log | Select-String " ==>  ") -ne $null) { 
          Throw "Errors were found during tests";
        }


  luacheck:

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'linux'
            vm: 'ubuntu-22.04'
          - os: 'windows'
            vm: 'windows-latest'
    runs-on: ${{ matrix.vm }} 
      
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - run: sudo apt install luarocks
      if : matrix.os == 'linux'
      shell: bash
    - name: get luacheck.exe  # is also done in the travis script but in this action it does not run in bash
      if : matrix.os == 'windows'
      run: |
        mkdir cache
        C:msys64\usr\bin\wget.exe --tries=5 --timeout=10 --waitretry=10 --read-timeout=10 --retry-connrefused -O cache/luacheck.exe https://github.com/mpeterv/luacheck/releases/download/0.23.0/luacheck.exe
      shell: cmd
    - name: luacheck
      run: |
        PATH="/C/Program\ Files/Git/usr/bin:${PATH}"
        ./tools/travis/run-luacheck-${{ matrix.os }}.sh
      shell: bash



  doc_check:

    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
      
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - name: all_modules_linked
      run: ./tools/check_docs_module_linkage.sh
      shell: bash

